### ISSUE TITLE
Need to handle non UTF-8 characters

### ISSUE THREAD

**Issue by btilford** [ActivearkJWT/grunt-font-optimizer#4]
Using the following `chars` argument you get the error `Wide character in subroutine entry at Font/Subsetter.pm line 1496`

``` ABCDEFGHIJGKLMNOPQRSTUVWXYZabcdefghijgklmnopqrstuvwxyz 1234567890 ½¼ !@#$%^&*()-_=+'\";:,.<>/?[]{}\\|`~¡£¢§¶ªº°·± àáäâéèëêìíïîòóöôùúüûøßçæñÀÁÄÂÉÈËÊÌÍÏÎÒÓÖÔÙÚÜÛØÇÆÑ ®©¿™∞•–—≠⁄€ ‹›ﬁﬂ‡‚± “” ‘’ œ …≤≥```

Using Perl 5.18.2
NodeJS 0.10.32

**Comment by jehna** [comment]
From a quick look, I'd say the bug is on the [Google Font Directory's](https://code.google.com/p/googlefontdirectory/) code.

Updating the Google Font Directory code could also fix the bug

**Comment by btilford** [comment]
It's actually the argument passed to the perl script that needs to be encoded.

**Comment by jehna** [comment]
Yes, silly me, remembered a whole another project. Sorry about that.

**Comment by jehna** [comment]
Remembering more, this project was originally based on Google Font Directory's code. As a reminder from those times, there's still a faulty attribution reference in the readme file.

At some stage, the code was changed to use a perl library from Philip Taylor, but the attribution was somehow mixed to Google Font Directory.

Opening a new issue for the attribution, closing this one. Thank you @btilford for the fix!
